<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>12</LangVersion>
    <UseWPF>true</UseWPF>
    <RootNamespace>AutoProxy.App</RootNamespace>
    <AssemblyName>AutoProxy</AssemblyName>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
    <PackageReference Include="H.NotifyIcon.Wpf" Version="2.1.4" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\**\*.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AutoProxy.Core\AutoProxy.Core.csproj" />
    <ProjectReference Include="..\AutoProxy.Data\AutoProxy.Data.csproj" />
    <ProjectReference Include="..\AutoProxy.Windows\AutoProxy.Windows.csproj" />
  </ItemGroup>

</Project>